# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# We will use Ubuntu 18.04 (bionic beaver). List of options:
# https://docs.travis-ci.com/user/reference/overview/#linux
dist: bionic

# This enables the 'defaults' to test java applications:
language: java

# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: raouf25-github
    token:
      secure: EZ8/gyjgTlwgQXz7QqgorUn30esMEnmY9I5yA7r2532d9dorIuymynj/H2RZOfFBcLLvOIFXf1Xvn2ftnpYlshZcoJ2xwDOn/bwETMB2TggYujqhShscKyIykB03PWhW1Buyv4JUGLnW0ERKN3U/PyU0dQp80s3wp6Xv7ekM+6z3b0EegA5Clp/KPvC6gWlwwM1kITxDSwRjFAtF12EYvnbejO7ARAm8lkB+hSTJgwPzJMPvgPcfQ3Iaarm64wewBEagUVyXznz6Iqj4BNew/RMTsPFu4ZPjWg5/mn5Bf7fdYogehY9NB9NjVV5TjAnSbBkjdOC228Zp4FIbNry9vCHaMivD0T6TdjHFMvJoHPd/FIK7ood0uzGBVisQRtLrdxl04QTVPrHlbWwRclLMGw3ihqARN95cdLI33TzA+jMlOTr8Ih1izyJGJ+Q8ClRgB0fGz/RxNusebuinweh343kVcLd+ftsw8M0lttGgxtYhkdJiGTeBaLYDqT6kv5Aa9qYYUuyuTz8ZMtvXztgi82NoXXtk4cVStMhIuHAtPzbdoLJLpwwByaGnFgGmyHHZy3W0RYNJmSg9gbbkeKL1yGC74eb5tnC42FWGjBpzuENu1vNP94dWelWMe2X5CSeWJVU/L9CPtmt2fxynXVKDZkCnMEf0aDIwi1eLCeGhfMg=
      # encrypted value of your token

before_install:
- chmod +x mvnw
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Raouf25_Spring-Boot-efficient-search-API
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=Raouf25_Spring-Boot-efficient-search-API

after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
notifications:
  email:
    recipients:
      - makhlouf.raouf+travis@gmail.com
    #on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: QmOCHJ5jMn9a5itObvAFAmbMvDFGFLSPsDIsaWJyCxawg6V/20YG/UzTxvjFlzr/UFrrgfNyrSFErFAouce+S4vq9CGeofmAqTZKb6VrzhuOEXUCbWJtI6KBn5k3lziNY4gIhc/kOILsUV46ek0SyiApmpGBXEkKD1wMPgrZa1f8tNS4Bt8Cbjye79irQG5I8EOGXrdt5r5n4HwJRNg/uhVTbJNC7Fvcqfi2bN+e+rRJytC25yg0HFxn8tp9OfwAtW3PpL6CkTAVSV/8AIVscXg77sooHxnbiVWXn3K+xYLOtEPONinv9dgPyyOlH0mX32OsxnzR++/dKnEj8enr1OKtxFoyjMvqmr3Wvwsdc5NTBH8QmQ4lYllhC3D3Sa9wNpP37Ke5tgXXkwYdR4Anx1ilYyl4Zxk1hDvOylpyL5/HCjJkWrNn16omT9grTZSF98T5EuLnDwh4er+SV0b8SYm7NU+OZNVUa0NQaarwYGoijZ5JyfOlBrNMedRk39BKxizxQFrk2LaR4xM3SJ2b/1XrXOATNRvMu1RjKl2IaGqW4kNTECpSIb8efaenMWNIi1/EmMrjMFEegeQR1hnPu4ueTdrFIgQs13HZaveae7vV65SFG59WrQwuPiPoB8BOlnAgztbNjCDeuHQhtVYExyBa5D5HZTFnhFcUu/y3wZo=
  app: efficient-search-api
