#
# Build stage
#
FROM maven:3.8.7-eclipse-temurin-19 AS MAVEN_BUILD
COPY pom.xml /build/
COPY . /build/
WORKDIR /build/
#The option "--quiet" is used to limit the output to only warnings and errors (1)
RUN mvn -f /build/pom.xml clean package --quiet



#
# Package stage
#
FROM amazoncorretto:19.0.2-alpine
VOLUME /tmp
COPY  --from=MAVEN_BUILD /build/target/spring-boot-efficient-search-api-0.0.1-SNAPSHOT.jar  spring-boot-efficient-search-api.jar
ENTRYPOINT ["java","-jar","spring-boot-efficient-search-api.jar"]
