## Définir une variable globale pour le fichier JAR
ARG JAR_FILE=spring-boot-efficient-search-api-0.0.1-SNAPSHOT.jar

##
## Build stage
##
#FROM maven:3.9.11-eclipse-temurin-24-alpine AS maven_build
#COPY . /.
#RUN mvn clean package -DskipTests


FROM gcr.io/distroless/java21-debian12
USER nonroot:nonroot

ARG JAR_FILE
#COPY --from=maven_build --chown=nonroot:nonroot  ./target/${JAR_FILE} /app/app.jar
COPY --chown=nonroot:nonroot  ./target/${JAR_FILE} /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar",  "/app/app.jar" ]


# docker build -t spring-boot-efficient-search-api_3  . -f ./Dockerfile_3_distroless
# docker run -d -p 8333:8080  spring-boot-efficient-search-api_3

# docker images --filter=reference='spring-boot-efficient-search-api*' | sort

#[+] Building 5.6s (7/7) FINISHED