insert into car(type,country,manufacturer,create_date,model) values ('Small','Japan','Acura','1931-02-01','Integra');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Audi', '2019-06-12', 'A4');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Japan', 'Honda', '2020-01-02', 'Civic');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Republic of Korea', 'Hyundai', '2017-11-20', 'Elantra');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Ferrari', '2018-05-15', '458 Italia');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'United States of America', 'Ford', '2019-08-08', 'Explorer');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Volvo', '2017-09-25', 'V90');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Aston Martin', '2020-10-07', 'DB11');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Lexus', '2019-04-14', 'LC 500');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Mercedes-Benz', '2021-02-17', 'E-Class');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Republic of Korea', 'Kia', '2018-08-23', 'Sorento');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Lamborghini', '2017-07-11', 'Huracán');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United States of America', 'Chevrolet', '2020-09-30', 'Cruze');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Saab', '2019-11-29', '9-5');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Bentley', '2018-03-28', 'Continental');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Nissan', '2017-06-10', '370Z');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'BMW', '2021-01-01', '5 Series');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Republic of Korea', 'Genesis', '2020-07-17', 'GV80');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Maserati', '2019-09-08', 'GranTurismo');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United States of America', 'Tesla', '2018-04-24', 'Model 3');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Scania', '2017-02-11', 'P420');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Rolls-Royce', '2020-12-15', 'Phantom');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Mazda', '2019-05-23', 'MX-5');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Porsche', '2018-11-18', 'Panamera');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Republic of Korea', 'SsangYong', '2017-04-04', 'Korando');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Alfa Romeo', '2020-03-02', '4C');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United States of America', 'Dodge', '2019-10-19', 'Challenger');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Volvo', '2018-09-08', 'V60');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Jaguar', '2017-08-02', 'XJ');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Toyota', '2021-05-11', 'Supra');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'United States of America', 'Jeep', '2020-03-08', 'Grand Cherokee');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Audi', '2018-02-13', 'A6');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Republic of Korea', 'Kia', '2017-12-01', 'Rio');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Ferrari', '2019-07-22', '488 GTB');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'United States of America', 'GMC', '2018-06-14', 'Yukon');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Volvo', '2020-11-30', 'V60 Cross Country');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Rolls-Royce', '2019-03-26', 'Ghost');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Mazda', '2017-08-08', 'MX-5 RF');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Mercedes-Benz', '2018-11-07', 'S-Class');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Republic of Korea', 'Hyundai', '2020-04-12', 'Tucson');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Lamborghini', '2021-01-04', 'Aventador');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United States of America', 'Chevrolet', '2019-05-15', 'Spark');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Scania', '2021-02-09', 'R500');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Bentley', '2018-09-18', 'Mulsanne');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Nissan', '2020-10-22', 'GT-R');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Germany', 'Volkswagen', '2022-02-28', 'Touareg');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'France', 'Renault', '2021-09-15', 'Megane');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'United States of America', 'Dodge', '2020-12-10', 'Viper');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Italy', 'Fiat', '2019-05-01', '500');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Japan', 'Mitsubishi', '2018-08-16', 'Outlander');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Republic of Korea', 'Kia', '2017-11-28', 'Ceed');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Sweden', 'Volvo', '2020-02-22', 'S90');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Germany', 'Mercedes-Benz', '2019-06-05', 'S-Class');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Italy', 'Alfa Romeo', '2018-01-13', 'Giulia');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Japan', 'Lexus', '2017-12-20', 'RC');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'France', 'Peugeot', '2021-05-03', '308');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'United Kingdom of Great Britain and Northern Ireland', 'Land Rover', '2020-09-12', 'Discovery');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Germany', 'BMW', '2019-10-26', '3 Series');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United States of America', 'Cadillac', '2018-06-08', 'CT6');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Italy', 'Fiat', '2017-03-17', '124 Spider');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Japan', 'Nissan', '2021-07-14', 'Altima');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Republic of Korea', 'Hyundai', '2020-04-06', 'Genesis Coupe');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United Kingdom of Great Britain and Northern Ireland', 'Mini', '2019-01-19', 'Cooper');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'France', 'Citroen', '2018-07-23', 'C5 Aircross');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Japan', 'Toyota', '2017-09-08', 'Corolla Touring Sports');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Audi', '2020-12-30', 'A8');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Republic of Korea', 'Kia', '2019-04-18', 'Stinger');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Russian Federation', 'Lada', '2021-09-01', 'Niva');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Spain', 'SEAT', '2019-12-28', 'Leon');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'France', 'Peugeot', '2018-06-09', '308');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Switzerland', 'Rinspeed', '2020-07-05', 'SQuba');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Canada', 'Dodge', '2019-01-12', 'Charger');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Norway', 'Kongsberg', '2017-05-20', 'Hydrogen Fuel Cell');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'India', 'Mahindra', '2021-03-15', 'Thar');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'China', 'Geely', '2018-02-22', 'GC9');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Sweden', 'Koenigsegg', '2020-04-11', 'Gemera');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'United States of America', 'Jeep', '2020-03-15', 'Grand Cherokee');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Japan', 'Honda', '2019-08-21', 'Fit');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Italy', 'Fiat', '2018-06-17', '124 Spider');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Germany', 'Audi', '2017-02-09', 'TT');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Republic of Korea', 'Kia', '2021-09-01', 'K5');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Volvo', '2019-12-10', 'V90 Cross Country');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'United Kingdom of Great Britain and Northern Ireland', 'Aston Martin', '2018-11-05', 'Vantage');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Japan', 'Mitsubishi', '2017-10-28', 'Outlander');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Germany', 'Volkswagen', '2020-07-06', 'Golf');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United States of America', 'Cadillac', '2019-05-12', 'CT6');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Republic of Korea', 'Hyundai', '2018-04-08', 'Genesis');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Italy', 'Maserati', '2017-06-19', 'Levante');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Sweden', 'Koenigsegg', '2018-08-30', 'Jesko');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Japan', 'Lexus', '2021-02-03', 'ES');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United Kingdom of Great Britain and Northern Ireland', 'MINI', '2019-11-16', 'Cooper');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Germany', 'Mercedes-Benz', '2017-03-20', 'GLC');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Republic of Korea', 'Kia', '2018-05-24', 'Stinger');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'United States of America', 'Ford', '2020-12-08', 'Mustang');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Italy', 'Ferrari', '2019-01-25', '488 Spider');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Japan', 'Toyota', '2017-07-22', 'Camry');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Sweden', 'Volvo', '2018-09-03', 'XC40');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'United Kingdom of Great Britain and Northern Ireland', 'Bentley', '2020-06-12', 'Bentayga');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Germany', 'BMW', '2017-12-30', 'M4');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Italy', 'Alfa Romeo', '2019-10-18', 'Giulia');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Japan', 'Nissan', '2018-02-14', 'GT-R');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'United States of America', 'Chevrolet', '2021-08-09', 'Tahoe');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Republic of Korea', 'Hyundai', '2017-04-02', 'Accent');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Porsche', '2018-07-26', '911');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Sweden', 'Koenigsegg', '2019-05-20', 'Regera');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'United Kingdom of Great Britain and Northern Ireland', 'Land Rover', '2020-01-08', 'Range Rover');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Canada', 'Ford', '2016-06-18', 'Explorer');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'BMW', '2017-02-04', '3 Series');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Japan', 'Honda', '2018-08-23', 'Fit');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Italy', 'Ferrari', '2019-05-30', 'California');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Republic of Korea', 'Hyundai', '2020-03-14', 'Sonata');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'United States of America', 'Dodge', '2017-09-21', 'Charger');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Volvo', '2021-02-08', 'V60 Cross Country');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Bentley', '2019-11-07', 'Mulsanne');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Nissan', '2017-04-22', 'GT-R');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Audi', '2018-07-09', 'A6');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Republic of Korea', 'Kia', '2019-01-28', 'Telluride');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Lamborghini', '2017-08-16', 'Aventador');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United States of America', 'Chevrolet', '2021-03-02', 'Spark');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Saab', '2018-09-14', '9-3');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Rolls-Royce', '2020-05-25', 'Ghost');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Mazda', '2017-06-09', 'MX-5 RF');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Mercedes-Benz', '2019-08-02', 'S-Class');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Republic of Korea', 'Genesis', '2018-12-30', 'GV70');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Maserati', '2021-07-19', 'GranCabrio');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United States of America', 'Tesla', '2017-11-12', 'Model S');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Scania', '2019-05-06', 'R730');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Jaguar', '2021-01-08', 'XF');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Toyota', '2018-04-15', '86');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Canada', 'Jeep', '2020-10-03', 'Grand Cherokee');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Porsche', '2017-07-17', '911');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Japan', 'Nissan', '2019-11-22', 'Leaf');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Republic of Korea', 'SsangYong', '2018-08-09', 'Rexton');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Alfa Romeo', '2017-03-28', 'Giulia');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United States of America', 'Cadillac', '2021-04-06', 'CT4');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Germany', 'BMW', '2019-02-12', '4 Series');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Germany', 'Porsche', '2016-09-13', '911');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'United States of America', 'Jeep', '2018-02-27', 'Grand Cherokee');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Republic of Korea', 'Kia', '2020-12-04', 'Rio');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Italy', 'Ferrari', '2017-08-23', 'California');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Japan', 'Toyota', '2019-05-31', 'Camry');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Volvo', '2021-01-09', 'XC70');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Aston Martin', '2018-06-21', 'Vantage');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Germany', 'Mercedes-Benz', '2017-03-17', 'GLC');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Lamborghini', '2020-09-02', 'Aventador');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United States of America', 'Chevrolet', '2019-10-05', 'Spark');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Scania', '2018-07-19', 'R500');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Rolls-Royce', '2017-12-14', 'Ghost');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Nissan', '2018-03-28', 'GT-R');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'BMW', '2019-07-26', '7 Series');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Republic of Korea', 'Hyundai', '2020-06-10', 'Tucson');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Maserati', '2017-09-12', 'GranCabrio');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United States of America', 'Ford', '2018-10-17', 'Fiesta');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Volvo', '2019-11-06', 'XC90');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Jaguar', '2020-08-08', 'XE');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Honda', '2017-02-03', 'S2000');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Audi', '2018-12-20', 'A6');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Republic of Korea', 'Kia', '2019-06-18', 'Telluride');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Italy', 'Alfa Romeo', '2020-01-07', 'Giulia');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'United States of America', 'Tesla', '2017-04-23', 'Model S');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Sweden', 'Scania', '2021-03-05', 'G450');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United Kingdom of Great Britain and Northern Ireland', 'Bentley', '2018-09-12', 'Mulsanne');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Mazda', '2020-05-29', 'MX-5 RF');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Germany', 'Porsche', '2017-07-21', 'Panamera Sport Turismo');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'South Africa', 'Toyota', '2022-02-15', 'Etios');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Australia', 'Holden', '2021-01-07', 'Acadia');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Canada', 'Chrysler', '2019-06-28', '300');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'France', 'Renault', '2020-09-01', 'Talisman');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Germany', 'Volkswagen', '2021-11-12', 'Golf Variant');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Republic of Korea', 'SsangYong', '2018-03-17', 'Tivoli');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Japan', 'Subaru', '2019-10-30', 'Legacy');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Italy', 'Fiat', '2020-08-22', '124 Spider');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Mexico', 'Nissan', '2018-04-19', 'Versa');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Russian Federation', 'Lada', '2022-03-01', 'Vesta');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'Spain', 'Seat', '2019-07-05', 'Leon SC');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Sweden', 'Volvo', '2017-12-23', 'XC60');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'United Kingdom of Great Britain and Northern Ireland', 'MG', '2021-02-14', 'MG5');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'United States of America', 'Buick', '2018-06-09', 'Regal');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Germany', 'BMW', '2020-07-28', '4 Series');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Japan', 'Suzuki', '2019-09-16', 'Swift');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Republic of Korea', 'Kia', '2017-10-25', 'Optima');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'United States of America', 'Dodge', '2018-01-11', 'Charger');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'United Kingdom of Great Britain and Northern Ireland', 'Land Rover', '2021-09-02', 'Defender');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Italy', 'Alfa Romeo', '2019-04-07', 'Stelvio');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'France', 'Peugeot', '2018-08-14', '508');
insert into car(type,country,manufacturer,create_date,model) values ('Convertible', 'Japan', 'Honda', '2020-12-18', 'S2000');
insert into car(type,country,manufacturer,create_date,model) values ('Hatchback', 'Germany', 'Opel', '2021-03-10', 'Astra');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Republic of Korea', 'Hyundai', '2017-05-03', 'Sonata');
insert into car(type,country,manufacturer,create_date,model) values ('Coupe', 'United States of America', 'Ford', '2020-04-25', 'Mustang');
insert into car(type,country,manufacturer,create_date,model) values ('SUV', 'Canada', 'Ford', '2019-02-08', 'Expedition');
insert into car(type,country,manufacturer,create_date,model) values ('Wagon', 'Japan', 'Toyota', '2022-01-06', 'Prius V');
insert into car(type,country,manufacturer,create_date,model) values ('Sedan', 'Sweden', 'Saab', '2018-09-13', '9-3');
